/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.ese.android.model.android.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.ese.android.model.android.Activity;

/**
 * A sample validator interface for {@link org.eclipse.ese.android.model.android.Application}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApplicationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateActivities(EList<Activity> value);
}
