grammar org.eclipse.ese.Android with org.eclipse.xtext.common.Terminals 

import "platform:/resource/org.eclipse.ese.android.model/model/android.ecore" 
	
Application:
	'Application' name=ID activities+=Activity+;

Activity:
	'Activity' name=ID '{' widgets+=Widget* '}';

Widget:
	Text | Button | Spinner | Link;

Text:
	'Text' name=ID;

Button:
	'Button' name=ID;

Spinner:
	'Spinner' name=ID;

Link:
	'Link' name=ID '->' activity=[Activity];
    
