/*
 * generated by Xtext
 */
package org.eclipse.ese;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AndroidRuntimeModule extends org.eclipse.ese.AbstractAndroidRuntimeModule {

}
