/*
 * generated by Xtext
 */
package org.eclipse.ese.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.ese.android.model.android.Application;
import org.eclipse.ese.validation.AndroidJavaValidator;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

/**
 * Creates quick fixes for selected validation issues.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#quickfixes
 */
public class AndroidQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(AndroidJavaValidator.CAPITALIZE)
	public void capitalizeName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Capitalize name", "Capitalize the name.", "actions/upcase.gif", new ISemanticModification() {
			public void apply(EObject element, IModificationContext context) {
				Application application = (Application) element;
				String name = application.getName();
				application.setName(name.substring(0,1).toUpperCase() + name.substring(1));
			}
		});
	}

	@Fix(AndroidJavaValidator.REMOVE_ELEMENT)
	public void removeLink(final Issue issue, IssueResolutionAcceptor acceptor) {
		String typeName = issue.getData()[0];
		acceptor.accept(issue, "Remove " + typeName, "Remove this "+ typeName +".", "actions/delete.gif", new ISemanticModification() {
			public void apply(EObject element, IModificationContext context) throws Exception {
				EcoreUtil.remove(element);
			}
		});
	}

}
