/*
* generated by Xtext
*/
package org.eclipse.ese.ui.labeling;

import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class AndroidDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
	
	@Override
	public Object image(IEObjectDescription element) {
		return AndroidLabelProvider.ICON_BASE_FOLDER + element.getEClass().getName() + ".gif";
	}
	
	public String getText(Object element) {
		String text = super.getText(element);
		if((text.startsWith("'") && text.endsWith("'"))
				|| (text.startsWith("\"") && text.endsWith("\""))) {
			return text.substring(1, text.length()-1);
		}
		return text;
	}
}
