/*
 * generated by Xtext
 */
package org.eclipse.ese.ui.labeling;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class AndroidLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public AndroidLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	protected Object doGetImage(Object element) {
		if (element instanceof EObject) {
			return ((EObject) element).eClass().getName() + ".gif";
			
		}
		return super.doGetImage(element);
	}

}
